# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "6df700477f7e1b2aa5c8de4809ee68c9"
name = "testing-bundle-app"
handle = "testing-bundle-app"
application_url = "https://step-texts-requires-lowest.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "store-crafters.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://step-texts-requires-lowest.trycloudflare.com/auth/callback",
  "https://step-texts-requires-lowest.trycloudflare.com/auth/shopify/callback",
  "https://step-texts-requires-lowest.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
